#!/usr/bin/python3
"""
1. My list
Write a class MyList that inherits from list
"""


class MyList(list):
    pass
def print_sorted(self):
    """prints the list, but sorted (ascending sort)"""
    list.sort()
    print()
